import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("brightsmile", "routes/brightsmile.tsx"),
  route("brightsmile-vtwo", "routes/brightsmile-vtwo.tsx"),
  route("brightsmile-vthree", "routes/brightsmile-vthree.tsx"),
  route("adminBrightSmile", "routes/adminBrightSmile.tsx"),
  route("adminBrightSmile-LRN", "routes/adminBrightSmile-LRN.tsx"),
  route("aldrenbagual-v1", "routes/aldrenbagual-v1.tsx"),
  route("aldrenbagual-v2", "routes/aldrenbagual-v2.tsx"),
  route("adminBrightSmile-v1", "routes/adminBrightSmile-v1.tsx"),
  route("adminBrightSmile-v2", "routes/adminBrightSmile-v2.tsx"),
  route("adminMenu", "routes/adminMenu.tsx"),
  route("para", "routes/para.tsx"),
  route("para2", "routes/para2.tsx"),
  route("para3", "routes/para3.tsx"),
  route("questionnaire", "routes/questionnaire.tsx"),
  route("pcs", "routes/pcs.tsx"),
  route("pcs2", "routes/pcs2.tsx"),
  route("pcs3", "routes/pcs3.tsx"),
  route("pcs4", "routes/pcs4.tsx"),
  route("pcs5", "routes/pcs5.tsx"),
  route("linkedin-kit", "routes/linkedin-kit.jsx"),
  route("linkedin-featured", "routes/linkedin-featured.jsx"),
  route("linkedin-kit-v2", "routes/linkedin-kit-v2.jsx"),
  route("linkedin-post-composer", "routes/linkedin-post-composer.jsx"),
] satisfies RouteConfig;
